import { chromium } from "@playwright/test";
const url = process.argv[2];
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const authCalls = [];
page.on("response", (r) => { if (r.url().includes("/auth/")) authCalls.push(`${r.request().method()} ${new URL(r.url()).pathname} ${r.status()}`); });
await page.goto(url);
await page.waitForTimeout(6000);
const me = await page.evaluate(async () => (await fetch("/api/v1/company/auth/me")).status);
console.log("final url:", page.url());
console.log("auth calls:", authCalls.join(" | "));
console.log("GET auth/me ->", me);
await page.screenshot({ path: process.argv[3] });
await browser.close();
